version: "3.9"

services:
  buzzbot:
    build: .
    container_name: buzzbot
    ports:
      - "8000:8000"
    volumes:
      - ./vector_store:/app/vector_store
      - ./prompts:/app/prompts
      - ./config:/app/config
    environment:
      - API_KEY=${API_KEY}
      - USE_GEMINI=${USE_GEMINI}
      - MODEL_VARIANT=${MODEL_VARIANT}
    restart: unless-stopped
