version: "3.9"
services:
  buzzbot:
    container_name: buzzbot
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./vector_store:/app/vector_store
      - ./prompts:/app/prompts
      - ./config:/app/config
      - ./models:/app/vector_store/models
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    restart: unless-stopped
